### ISSUE TITLE
I'm still getting this error on the lists page.  Version 1.9.9

### ISSUE THREAD

**Issue by midweste** [mailgun/wordpress-plugin#178]
I'm still getting this error on the lists page.  Version 1.9.9

```
Fatal error: Uncaught Error: Call to undefined function mg_api_get_region() in /app/web/wp-content/plugins/mailgun/mailgun.php:222
Stack trace:
#0 /app/web/wp-content/plugins/mailgun/mailgun.php(286): Mailgun->api_call('lists', Array, 'GET')
#1 /app/web/wp-content/plugins/mailgun/includes/lists-page.php(38): Mailgun->get_lists()
#2 /app/web/wp-content/plugins/mailgun/includes/admin.php(234): include('/app/web/wp-con...')
#3 /app/web/wp-includes/class-wp-hook.php(324): MailgunAdmin->lists_page('')
#4 /app/web/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /app/web/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /app/web/wp-admin/admin.php(259): do_action('admin_page_mail...')
#7 {main}
  thrown in /app/web/wp-content/plugins/mailgun/mailgun.php on line 222
```

_Originally posted by @midweste in https://github.com/mailgun/wordpress-plugin/issues/164#issuecomment-2052466704_

**Comment by oleksandr-mykhailenko** [comment]
This one is fixed
